name: Trigger auto deployment for workbench-langflow-container

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ dev ]
    paths:
    - '**'
    - '.github/workflows/workbench-langflow-container-AutoDeployTrigger-30be5752-14fc-4da4-8ed5-774a2d6b83ec.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.WORKBENCHLANGFLOWCONTAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.WORKBENCHLANGFLOWCONTAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.WORKBENCHLANGFLOWCONTAINER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: workbenchazureregistry.azurecr.io
          registryUsername: ${{ secrets.WORKBENCHLANGFLOWCONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.WORKBENCHLANGFLOWCONTAINER_REGISTRY_PASSWORD }}
          containerAppName: workbench-langflow-container
          resourceGroup: Container-App-Resource-group
          imageToBuild: workbenchazureregistry.azurecr.io/workbench-langflow-container:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


