name: Trigger auto deployment for workbench-langflow-container

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ dev ]
    paths:
    - '**'
    - '.github/workflows/workbench-langflow-container-AutoDeployTrigger-f6800369-b92b-4760-b359-e66658001a40.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.WORKBENCHLANGFLOWCONTAINER_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: workbenchazureregistry.azurecr.io
          registryUsername: ${{ secrets.WORKBENCHLANGFLOWCONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.WORKBENCHLANGFLOWCONTAINER_REGISTRY_PASSWORD }}
          containerAppName: workbench-langflow-container
          resourceGroup: Container-App-Resource-group
          imageToBuild: workbenchazureregistry.azurecr.io/workbench-langflow-container:${{ github.sha }}
          
            

     

